config/routes.rb
Rails.application.routes.draw do
  root 'animals#index'

  devise_for :zoos
  
  resources :animals 
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :zoo

  validates :age, numericality: { greater_than_or_equal_to: 2, message: "of Animal must be 2 at least, unless born within the Zoo." }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/zoo.rb
class Zoo < ApplicationRecord
  has_many :animals
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  def index
    @animals = current_zoo.animals 
  end

  def show
  end

  def new
    @animal = Animal.new 
  end

  def create 
    @animal = current_zoo.animals.new(animal_params)
    if @animal.save 
      flash[:success] = "- - Animal Has Been Captured - -"
      redirect_to animals_path
    else 
      flash[:error] = "!FAILED! Animal not captured. #{@animal.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def edit
  end

  def update 
    if @animal.update(animal_params)
      redirect_to animals_path 
    else 
      render :edit
    end
  end 

  def destroy 
    @animal.destroy 
    redirect_to animals_path
  end

  private 

    def animal_params 
      params.require(:animal).permit(:name, :species, :age)
    end

    def set_animal 
      @animal = current_zoo.animals.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_zoo!

  protected 
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:keeper_name])
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/edit.html.erb
<h1>Animals#edit</h1>
<p>Find me in app/views/animals/edit.html.erb</p>

app/views/animals/index.html.erb
<div class="box">

  <%= button_to "Log Out", destroy_zoo_session_path, method: :delete, class: "ui inverted red button" %>

  <h2> Welcome <%= current_zoo.keeper_name %> </h2>

  <%= link_to "Capture New Exotic Animal", new_animal_path, class: "ui inverted teal button" %>

  <h3> Your Animal </h3> 

  <% @animals.each do |animal| %>

    <div id="animal-desc">
      <%= animal.name %> - <%= animal.species %> <%= animal.age %> 
      <a><%= link_to animal.name, animal %></a>
    </div>

  <% end %>

</div>

app/views/animals/new.html.erb
<div class="box">
  <h1>Capturing a New Exotic Animal </h1>

  <%= form_with(model: @animal, local: true) do |f| %>

    <div class="ui transparent input" id="mango">
      <%= f.label :name %>
      <%= f.text_field :name, required: true %>
    </div>

    <div class="ui transparent input" id="mango">
      <%= f.label :species %>
      <%= f.text_field :species, required: true %>
    </div>

    <div class="ui transparent input" id="mango">
      <%= f.label :age %>
      <%= f.text_field :age, required: true %>
    </div>

    <p id="submit"><%= f.submit %></p>

  <% end %>

</div>

app/views/animals/show.html.erb
<p id="release"><%= link_to 'Release Back Into Wild', @animal, method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menegerie_Tycoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>